//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace InternshipApplicationPlatform.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Company
    {
        public int CompanyId { get; set; }
        public string Signature { get; set; }
        public string CompanyName { get; set; }
        public Nullable<System.DateTime> Date { get; set; }
        public Nullable<int> InternshipId { get; set; }
        public string Tel { get; set; }
        public string Adress { get; set; }
        public string YetkiliImg { get; set; }
        public string Logo { get; set; }
        public string FirmaMail { get; set; }
        public string YetkiliEmail { get; set; }
        public string YetkiliTel { get; set; }
        public string Meslek { get; set; }
        public string YetkiliName { get; set; }
        public string YetkiliSurname { get; set; }
    }
}
