//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace InternshipApplicationPlatform.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Internship
    {
        public int InternshipId { get; set; }
        public Nullable<int> UserId { get; set; }
        public string AcademicYear { get; set; }
        public Nullable<int> StudentId { get; set; }
        public Nullable<int> CompanyId { get; set; }
        public Nullable<int> DepartmentId { get; set; }
        public Nullable<int> FacultyId { get; set; }
        public Nullable<System.DateTime> Date { get; set; }
        public string StudentName { get; set; }
        public string StudentSurname { get; set; }
        public string StudentDepartment { get; set; }
        public string StudentTel { get; set; }
        public string StudentMail { get; set; }
        public string StudentsAddress { get; set; }
        public Nullable<System.DateTime> DeliveryDateToTheCompany { get; set; }
        public string StudentSignature { get; set; }
        public string CompanyName { get; set; }
        public string CompanyTel { get; set; }
        public string CompanyAddres { get; set; }
        public string CompanyGuyName { get; set; }
        public string CompanyGuySurname { get; set; }
        public string CompanyGuyTitle { get; set; }
        public string CompanyGuyMail { get; set; }
        public string CompanyGuySignature { get; set; }
        public Nullable<System.DateTime> CompanyApprovalDate { get; set; }
        public Nullable<int> InternshipTime { get; set; }
        public Nullable<System.DateTime> InternshipStart { get; set; }
        public Nullable<System.DateTime> InternshipEnd { get; set; }
        public string Transcript { get; set; }
        public string Cv { get; set; }
        public string StudentTC { get; set; }
        public string StudentSSK { get; set; }
        public string StudentFather { get; set; }
        public string StudentsMother { get; set; }
        public string StudentsPlaceOfBirth { get; set; }
        public Nullable<System.DateTime> StudentsDateOfBirth { get; set; }
        public string StudentsHealthInsurance { get; set; }
        public string StudentImg { get; set; }
        public string DepartmentCommitteeChairmanName { get; set; }
        public string DepartmentCommitteeChairmanSignature { get; set; }
        public Nullable<System.DateTime> DepartmentCommitteeChairmanApproval { get; set; }
        public string DeaneryName { get; set; }
        public string DeanerySignature { get; set; }
        public Nullable<System.DateTime> DeaneryApproval { get; set; }
        public string HeadOfDepartmentName { get; set; }
        public string HeadOfDepartmentSignature { get; set; }
        public Nullable<System.DateTime> HeadOfDepartmentApproval { get; set; }
        public string Status { get; set; }
        public Nullable<bool> IsComplete { get; set; }
    }
}
