//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace InternshipApplicationPlatform.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Student
    {
        public int StudentId { get; set; }
        public Nullable<int> UserId { get; set; }
        public Nullable<int> InternshipId { get; set; }
        public string No { get; set; }
        public Nullable<int> DepartmentId { get; set; }
        public string SSK { get; set; }
        public string FatherName { get; set; }
        public string MotherName { get; set; }
        public string PlaceOfBirth { get; set; }
        public Nullable<System.DateTime> DateOfBirth { get; set; }
        public string HealthInsurance { get; set; }
        public string Transcript { get; set; }
        public string CV { get; set; }
        public string StudentImg { get; set; }
    }
}
